<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 1
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro*)> <!-- La biblioteca tiene 1 o más libros -->
    <!ELEMENT libro (titulo, editorial, autor, numero_paginas)> <!-- Cada libro tiene título, editorial, autor y número de páginas -->
    <!ELEMENT titulo (#PCDATA)> <!-- El título -->
    <!ELEMENT editorial (#PCDATA)> <!-- La editorial -->
    <!ELEMENT autor (nombre, apellidos)> <!-- El nombre y apellidos del autor -->
    <!ELEMENT nombre (#PCDATA)> <!-- El nombre del autor -->
    <!ELEMENT apellidos (#PCDATA)> <!-- Los apellidos del autor -->
    <!ELEMENT numero_paginas (#PCDATA)> <!-- Número de páginas -->
]>
<biblioteca> <!-- Inicio de la lista de libros -->
    <libro>
        <titulo>Historia de una escalera</titulo>
        <editorial>Austral</editorial>
        <autor>
            <nombre>Antonio</nombre>
            <apellidos>Buero Vallejo</apellidos>
        </autor>
        <numero_paginas>160</numero_paginas>
    </libro>
    <libro>
        <titulo>La casa de Bernarda Alba</titulo>
        <editorial>Cátedra</editorial>
        <autor>
            <nombre>Federico</nombre>
            <apellidos>García Lorca</apellidos>
        </autor>
        <numero_paginas>144</numero_paginas>
    </libro>
    <libro>
        <titulo>La familia de Pascual Duarte</titulo>
        <editorial>Editorial Planeta</editorial>
        <autor>
            <nombre>Camilo José</nombre>
            <apellidos>Cela</apellidos>
        </autor>
        <numero_paginas>192</numero_paginas>
    </libro>
</biblioteca>