=== Elenaqr/1DAMLDM/XML/XML-DTDII/ejercicio3/ejercicio3.dtd
<!-- Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 3
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE ejercicio3 [
    <!ELEMENT panel (nombre_aeropuerto, fecha, vuelos)> <!-- El elemento raíz -->
    <!ELEMENT nombre_aeropuerto (#PCDATA)> <!-- Nombre del aeropuerto -->
    <!ELEMENT fecha (#PCDATA)> <!-- Fecha del panel de vuelos -->
    <!ELEMENT vuelos (vuelo+)> <!-- Con 1 o más elementos 'vuelo' -->
    <!ELEMENT vuelo (origen, destino, salida, llegada)> <!-- Cada vuelo tiene origen, destino, hora de salida y hora de llegada -->
    <!ATTLIST vuelo codigo ID #REQUIRED> <!-- Código del vuelo (obligatorio) --> estado (C | E | R) #REQUIRED> <!-- Estado del vuelo: C (Cancelado), E (En vuelo), R (Retrasado) (obligatorio) -->
    <!ELEMENT origen (#PCDATA)> <!-- Ciudad de origen del vuelo -->
    <!ELEMENT destino (#PCDATA)> <!-- Ciudad de destino del vuelo -->
    <!ELEMENT salida (#PCDATA)> <!-- Hora de salida del vuelo -->
    <!ELEMENT llegada (#PCDATA)> <!-- Hora de llegada del vuelo -->
]>

=== Elenaqr/1DAMLDM/XML/XML-DTDII/ejercicio3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel SYSTEM "ejercicio3.dtd">
<panel>
    <nombre_aeropuerto>JFK</nombre_aeropuerto>
    <fecha>20/12/2013</fecha>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <origen>New York</origen>
            <destino>Chicago</destino>
            <salida>09:30</salida>
            <llegada>11:30</llegada>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <salida>10:15</salida>
            <llegada>11:15</llegada>
        </vuelo>
    </vuelos>
</panel>
