<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 05/04/2025
Ejercicio: Ejercicio 2-5
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE reyesEspañoles [
    <!ELEMENT reyesEspañoles (rey*, reina*)> <!-- Elemento raíz 'reyesEspañoles' tiene 0 o más elementos 'rey' y elementos 'reina' --> 
    <!ELEMENT rey (nombre, padre, madre)> <!-- Elemento 'rey' tiene un elemento 'nombre', un elemento 'padre' y un elemento 'madre' -->
    <!ELEMENT reina (nombre, padre, madre)> <!-- Elemento 'reina' tiene un elemento 'nombre', un elemento 'padre' y un elemento 'madre' -->
    <!ELEMENT nombre (#PCDATA)> <!-- Elemento 'nombre' tiene una nombre -->
    <!ELEMENT padre (#PCDATA)> <!-- Elemento 'padre' tiene un padre -->
    <!ELEMENT madre (#PCDATA)> <!-- Elemento 'madre' tiene una madre -->
]>
<reyesEspañoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana la loca</nombre>
        <padre>Fernando el Católico</padre>
        <madre>Isabel la Católica</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juana la Loca</madre>
    </rey>
</reyesEspañoles> 