<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 05/04/2025
Ejercicio: Ejercicio 2-2
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE efemerides [
    <!ELEMENT efemerides (efemeride*)> <!-- Elemento raíz 'efemerides' tiene 0 o más elementos 'efemeride' --> 
    <!ELEMENT efemeride (fecha, hecho)> <!-- Elemento 'efemeride' tiene un elemento 'fecha' y un elemento 'hecho' -->ç
    <!ELEMENT fecha (#PCDATA)> <!-- Elemento 'fecha' tiene una fecha -->
    <!ELEMENT hecho (#PCDATA)> <!-- Elemento 'hecho' tiene un hecho -->
]>
<efemerides>
    <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>Llegada del hombre a la Luna</hecho>
    </efemeride>
    <efemeride>
        <fecha>12 de octubre de 1492</fecha>
        <hecho>Llegada de Colón a América</hecho>
    </efemeride>
    <efemeride>
        <fecha>6 de abril de 1909</fecha>
        <hecho>Llegada de Robert Peary al Polo Norte</hecho>
    </efemeride>
</efemerides> 