=== Elenaqr/1DAMLDM/XML/XML-DTDI/ejercicio3/ejercicio3.dtd
<!-- Nombre: Elena Qin Real Zhang -->
<!-- Curso: 1DAM -->
<!-- Fecha: 03/04/2025 -->
<!-- Ejercicio: Ejercicio 3 -->
<!-- Cambio: Se agregó la documentación necesaria -->

<!DOCTYPE agenda [
    <!ELEMENT agenda (nombre, apellido+, telefono, fecha_nacimiento, lugar_nacimiento)> <!-- El elemento raíz --> 
    <!ELEMENT nombre (#PCDATA)> <!-- El nombre de la persona -->
    <!ELEMENT apellido (#PCDATA)> <!-- Los apellidos de la persona (puede haber más de uno) -->
    <!ELEMENT telefono (#PCDATA)> <!-- El número de teléfono de la persona -->
    <!ELEMENT fecha_nacimiento (anio, mes, dia)> <!-- La fecha de nacimiento de la persona, dividida en año, mes y día -->
    <!ELEMENT anio (#PCDATA)> <!-- El año de nacimiento -->
    <!ELEMENT mes (#PCDATA)> <!-- El mes de nacimiento -->
    <!ELEMENT dia (#PCDATA)> <!-- El día de nacimiento -->
    <!ELEMENT lugar_nacimiento (pais, ciudad, localidad)> <!-- El lugar de nacimiento de la persona, dividido en país, ciudad y localidad -->
    <!ELEMENT pais (#PCDATA)> <!-- El país de nacimiento -->
    <!ELEMENT ciudad (#PCDATA)> <!-- La ciudad de nacimiento -->
    <!ELEMENT localidad (#PCDATA)> <!-- La localidad de nacimiento -->
]>

=== Elenaqr/1DAMLDM/XML/XML-DTDI/ejercicio3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 3
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE agenda SYSTEM "ejercicio3.dtd"> <!-- Enlazando con la DTD externa -->
<agenda>
    <nombre>Antonio</nombre>
    <apellido>Sánchez</apellido>
    <apellido>Pérez</apellido>
    <telefono>666555444</telefono>
    <fecha_nacimiento>
        <anio>2000</anio>
        <mes>01</mes>
        <dia>20</dia>
    </fecha_nacimiento>
    <lugar_nacimiento>
        <pais>España</pais>
        <ciudad>Madrid</ciudad>
        <localidad>Getafe</localidad>
    </lugar_nacimiento>
</agenda>
