<?xml version="1.0" encoding="UTF-8"?>
<!-- Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 2
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE EquiposNBA [ <!-- Elemento raíz -->
    <!ELEMENT EquiposNBA (equipo | nombre)+> <!-- Contiene 1 o más equipos o nombres -->
    <!ELEMENT nombre (#PCDATA)> <!-- Nombre de un equipo -->
    <!ELEMENT equipo (titulos, posicion, quinteto)> <!-- Cada equipo tiene títulos, posición y quinteto -->
    <!ATTLIST equipo conferencia (Este | Oeste) #REQUIRED> <!-- Atributo obligatorio con la conferencia del equipo -->

    <!ELEMENT titulos (#PCDATA)> <!-- Número de títulos ganados -->
    <!ELEMENT posicion (#PCDATA)> <!-- Posición del equipo -->
    <!ELEMENT quinteto (#PCDATA)> <!-- Quinteto -->
]>
<EquiposNBA>
    <equipo conferencia="Este">
        <nombre>Atlanta Hawks</nombre>
        <titulos>1</titulos>
        <posicion>7</posicion>
        <quinteto>Dominique Wilkins, Bob Pettit, Dikembe Mutombo, Joe Johnson, Al Horford</quinteto>
    </equipo>
    
    <equipo conferencia="Oeste">
        <nombre>Los Angeles Lakers</nombre>
        <titulos>17</titulos>
        <posicion>Clasificado en playoffs</posicion>
        <quinteto> Johnson, Kobe Bryant, Kareem Abdul-Jabbar, Shaquille O'Neal, Jerry West</quinteto>
    </equipo>
</EquiposNBA>