=== Elenaqr/1DAMLDM/XML/XML-DTDIII/ejercicio1/ejercicio1-1y1-2.dtd
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 1
Cambio: Se agregó la documentación necesaria
-->
<!ELEMENT cuento (personajes, trama)> <!-- El elemento raíz -->
<!ELEMENT personajes (personaje+)> <!-- El elemento 'personajes' con 1 o más elementos 'personaje' -->
<!ELEMENT personaje (nombre, genero)> <!--  nombre y género del personaje -->
<!ELEMENT nombre (#PCDATA)> <!-- El nombre del personaje -->
<!ELEMENT genero (#PCDATA)> <!-- El género del personaje-->
<!ELEMENT trama (#PCDATA)> <!-- La trama del cuento -->
<!ATTLIST cuento cod CDATA #REQUIRED> <!-- El atributo 'cod' del elemento 'cuento' es obligatorio -->
<!ATTLIST cuento titulo CDATA #REQUIRED> <!-- El atributo 'titulo' del elemento 'cuento' es obligatorio -->
<!ATTLIST personaje id ID #REQUIRED> <!-- El atributo 'id' del elemento 'personaje' -->
<!ATTLIST personaje tipo (principal | secundario | antagonista) "principal"> <!-- El atributo 'tipo' del elemento 'personaje' puede ser:'principal', 'secundario', 'antagonista' -->

=== Elenaqr/1DAMLDM/XML/XML-DTDIII/ejercicio1/ejercicio1-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 1
Cambio: Se agregó la documentación necesaria
-->
<!DOCTYPE cuento SYSTEM "ejercicio1-1y1-2.dtd">
<!-- Enlazando con la DTD externa -->
<cuento cod="C1" titulo="El bosque encantado">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Juan</nombre>
            <genero>M</genero>
        </personaje>
        <personaje id="p2" tipo="secundario">
            <nombre>María</nombre>
            <genero>F</genero>
        </personaje>
    </personajes>
    <trama>Juan y María van a un lugar mágico con criaturas fantásticas.</trama>
</cuento>

=== Elenaqr/1DAMLDM/XML/XML-DTDIII/ejercicio1/ejercicio1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Elena Qin Real Zhang
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 1
Cambio: Se agregÃ³ la documentaciÃ³n necesaria
-->
<!DOCTYPE cuento SYSTEM "ejercicio1-1y1-2.dtd">
<!-- Enlazando con la DTD externa -->
<cuento cod="C2" titulo="La casa del terror">
    <personajes>
        <personaje id="p1" tipo="antagonista">
            <nombre>El fantasma</nombre>
            <genero>N</genero>
        </personaje>
        <personaje id="p2" tipo="principal">
            <nombre>Pedro</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>Pedro se enfrenta a un fantasma en una casa abandonada.</trama>
</cuento>
